name: 'Qiniu Upload'
description: 'Uploading files to qiniu'
author: 'OnekeyHq'
inputs:
  access_key:
    description: 'access key'
    required: true
  secret_key:
    description: 'secret key'
    required: true
  bucket:
    description: 'bucket'
    required: true
  source_dir:
    description: 'source dir'
    default: './'
    required: false
  dest_dir:
    description: 'dest dir, namely key prefix'
    default: '/'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
