name: 'Upload Firim File'
description: 'Upload artifacts to Firim'
author: 'OnekeyHq'
inputs:
  web-hook-url:
    description: 'Slack webhook url'
    required: true
  api-token:
    description: 'Account token for fir.im'
    required: true
  upload-file-path:
    description: 'The path to the uploaded file'
    required: true
  custom-host:
    description: 'Self-binding domain name'
    required: false
  changelog:
    description: 'Change log'
    required: false
  version-suffix:
    description: 'Version suffix'
    required: false
  use-release-id:
    description: 'The download link contains the Release ID'
    required: false
    default: true
  ios-release-type:
    description: 'Adhoc or Inhouse : IOS packaging type'
    required: false
    default: "Adhoc"
  custom-message-title:
    description: 'custom message title'
    required: false
  custom-message-payload:
    description: 'custom message payload'
    required: false
  custom-issue-url:
    description: 'custom issue url'
    required: false
outputs:
  artifact-download-url:
    description: 'Download link'
runs:
  using: "composite"
  steps:
    - name: get artifacts info
      uses: OneKeyHQ/onekey-github-actions/upload-artifact-firim@main
      id: artifacts_info
      with:
        artifact-file-path: ${{ inputs.upload-file-path }}

    - name: install firim & ruby
      uses: OneKeyHQ/onekey-github-actions/install-ruby-firim@main
      
    - name: upload firim
      id: upload_info
      run: |
        fir login ${{ inputs.api-token }} -R -c "${{ inputs.changelog }}" --specify-app-display-name="${steps.artifacts_info.outputs.artifact-version-name}-${{ inputs.version-suffix }}"
        egrep '(Published succeed: )\S+' grep_text.txt | egrep -o '(https?):\/\/[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]'
        export REGTEST_APK=`ls app/build/outputs/apk/RegTestOnekey/debug/*.apk`
        echo "::set-output name=artifact-download-url::$(echo $REGTEST_APK)"
