name: 'install ruby & firim'
description: 'install ruby & firim'
author: 'OnekeyHq'
runs:
  using: "install ruby & firim"
  steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.5
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.77.0
      with:
        ruby-version: 2.6.5
        bundler-cache: true
    - name: install fir.im
      run: gem install fir-cli
      