name: 'Upload Firim File'
description: 'Upload artifacts to Firim'
author: 'OnekeyHq'
inputs:
  api-token:
    description: 'Account token for fir.im'
    required: true
  upload-file-path:
    description: 'The path to the uploaded file'
    required: true
  changelog:
    description: 'Change log'
    required: false
  version-suffix:
    description: 'Version suffix'
    required: false
  use-release-id:
    description: 'The download link contains the Release ID'
    required: false
    default: false
  ios-release-type:
    description: 'Adhoc or Inhouse : IOS packaging type'
    required: false
    default: "Adhoc"
outputs:
  artifact-download-url:
    description: 'Download link'
  artifact-type:
    description: 'android or ios : An artifact type'
  artifact-bundle-id:
    description: 'android or ios : An artifact of the bundle id'
  artifact-version-code:
    description: 'android or ios : An artifact of the version code'
  artifact-version-name:
    description: 'android or ios : An artifact of the version name'
  artifact-name:
    description: 'android or ios : The name of an artifact'
runs:
  using: 'node12'
  main: 'index.js'